[package]
name = "tn"
version = "0.2.2"
edition = "2021"
description = "AI/ML"
license = "MIT"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
indicatif = "0.17.9"
libc = "0.2.169"
pyo3 = "0.23.4"
